<?php require_once 'partials/inc.header.php'; ?>

<span class="name">Mathieu BARBER, <?php echo $age; ?> ans</span>
<h1 data-animated>Développeur Web <abbr data-tooltip="Profil polyvalent et autonome capable d'intervenir sur toutes les facettes d'un site internet (back-end, front-end, bdd, business logic...)">full-stack</abbr><small>, <span class="nowrap" data-animated><?php echo $developperSinceYear; ?> ans d’expériences</span></small></h1>

<p class="highlight">Conception et réalisation d'applications <abbr data-tooltip="SaaS, API, outils métiers, sites internet">web</abbr> sur mesure</p>

<ul>
    <li>Spécialiste du framework <abbr data-tooltip="Framework PHP open-source basé sur de nombreux bundles Symfony"><strong>Laravel</strong></abbr>, <abbr data-tooltip="Framework JS comparable à Angular et React">Vue.js</abbr>, et divers <abbr data-tooltip="PHP, MySQL, Node.js, javascript, HTML5, CSS3, Sass, MongoDB...">langages</abbr></li>
    <li><strong>Curieux</strong> d'autres <abbr data-tooltip="Text&nbsp;generation (GPT-3, EleutherAI/GPT-Neo) et NLP (Natural Language Processing), Blockchains, Websockets...">technologies</abbr> et diverses <abbr data-tooltip="Bonnes pratiques de développement (SOLID principe, DRY) et méthode agile SCRUM...">méthodologies</abbr></li>
    <li>Habile en <strong class="abbr">référencement</strong> (naturel), graphisme <abbr data-tooltip="Expériences utilisateurs">(UI/UX)</abbr> et administration <abbr data-tooltip="Debian, Nginx, Serverless, AWS Lambda">serveur</abbr></li>
    <li><strong>Fondateur du site <a href="//www.fou-de-voyage.com" class="abbr" data-tooltip="En cours de refonte...">Fou de voyage</a></strong>, fort d’une communauté de 20 000 voyageurs passionnés</li>
</ul>

<div class="center">
    <form id="bonjour" action="/bonjour" method="POST" data-ajax>
        <fieldset>
            <legend>Contact</legend>
            <label>Name: <input type="text" name="name" value=""></label>
            <label>E-mail: <input type="text" name="email" value=""></label>
            <label>Message: <textarea name="message"></textarea></label>
        </fieldset>
        <input type="submit" value="Me contacter !" class="big">
    </form>
</div>


<div id="logos">
    <p style="opacity:0.75; color:#111; display: block" class="highlight"><small>Découvrez quelques missions en freelance réalisées sur mon profil <a href="https://www.linkedin.com/in/mathieubarber" target="_blank" data-tooltip="Voir mon profil LinkedIn">LinkedIn</a></small></p>
    <div class="ilovetax" alt="I love tax"></div>
    <div class="les-horaires" alt="Les-Horaires.fr"></div>
    <div class="ldlc" alt="LDLC"></div>
    <div class="argeles" alt="Argeles" <abbr data-tooltip="Développement des sites de la mairie et de l'office de Tourisme de la ville d'Argelès-sur-Mer."></div>
</div>


<?php require_once 'partials/inc.footer.php'; ?>
