<?php require_once 'partials/inc.header.php'; ?>

<h1>Mentions légales</h1>

<h2>Editeur</h2>
<p>Le site netfizz.fr est édité par l'entreprise individuelle NETFIZZ immatriculée au Registre du Commerce et des Sociétés de Lyon en février 2007 sous le numéro 494 460 819.<br />
    Siège social : 79, rue Pasteur - 69007 Lyon<br />
    SIRET : 494 460 819 00035<br />
    Tél : +33(0)9 80 68 09 29
</p>
<h2>Hébergeur</h2>
<p>Le site netfizz.fr est hébergé par la société OVH.<br />
    140, quai du Sartel 59100 ROUBAIX<br />
    Tél : 0 899 701 761<br />
    http://www.ovh.com
</p>

<?php require_once 'partials/inc.footer.php'; ?>
